CE103 Homework 3 Eray Turan: ce103_hw3_library_lib.Menu Class Reference
ce103_hw3_library_lib.Menu Class Reference
Public Member Functions
Menu (string prompt, string[] options)
void DisplayOptions ()
int Run ()
Constructor & Destructor Documentation
Menu()
ce103_hw3_library_lib.Menu.Menu (string prompt, string[] options)
Member Function Documentation
DisplayOptions()
void ce103_hw3_library_lib.Menu.DisplayOptions ()
Referenced by ce103_hw3_library_lib.Menu.Run().
Run()
int ce103_hw3_library_lib.Menu.Run ()
References ce103_hw3_library_lib.Menu.DisplayOptions(), and ce103_hw3_library_lib.library.Start().
Referenced by ce103_hw3_library_lib.library.BookOption(), and ce103_hw3_library_lib.library.RunMainMenu().
The documentation for this class was generated from the following file:
MainMenu.cs