CE103 Homework 3 Eray Turan: ce103_hw3_library_lib.FileUtility Class Reference
ce103_hw3_library_lib.FileUtility Class Reference
Static Public Member Functions
static bool DeleteFile (string path)
static byte[] ReadBlock (int count, int blocksize, string path)
static bool AppendBlock (byte[] data, string path)
static bool UpdateBlock (byte[] data, int count, int blocksize, string path)
static bool DeleteBlock (int count, int blocksize, string path)
Member Function Documentation
AppendBlock()
static bool ce103_hw3_library_lib.FileUtility.AppendBlock (byte[] data, string path) static
Referenced by ce103_hw3_library_lib.BookFunctions.AddBook().
DeleteBlock()
static bool ce103_hw3_library_lib.FileUtility.DeleteBlock (int count, int blocksize, string path) static
Referenced by ce103_hw3_library_lib.BookFunctions.DeleteBook().
DeleteFile()
static bool ce103_hw3_library_lib.FileUtility.DeleteFile (string path) static
ReadBlock()
static byte[] ce103_hw3_library_lib.FileUtility.ReadBlock (int count, int blocksize, string path) static
Referenced by ce103_hw3_library_lib.BookFunctions.BorrowBook(), ce103_hw3_library_lib.BookFunctions.ListBook(), ce103_hw3_library_lib.BookFunctions.ListBorrowBook(), ce103_hw3_library_lib.BookFunctions.ReturnBook(), and ce103_hw3_library_lib.BookFunctions.SearchBook().
UpdateBlock()
static bool ce103_hw3_library_lib.FileUtility.UpdateBlock (byte[] data, int count, int blocksize, string path) static
Referenced by ce103_hw3_library_lib.BookFunctions.BorrowBook(), ce103_hw3_library_lib.BookFunctions.EditBook(), and ce103_hw3_library_lib.BookFunctions.ReturnBook().
The documentation for this class was generated from the following file:
FileUtility.cs