CE103 Homework 3 Eray Turan: ce103_hw3_library_lib.BookFunctions Class Reference
ce103_hw3_library_lib.BookFunctions Class Reference
Public Member Functions
void AddBook ()
void EditBook ()
void ListBook ()
void DeleteBook ()
void BorrowBook ()
void ListBorrowBook ()
void SearchBook ()
void ReturnBook ()
Member Function Documentation
AddBook()
void ce103_hw3_library_lib.BookFunctions.AddBook ()
References ce103_hw3_library_lib.FileUtility.AppendBlock(), and ce103_hw3_library_lib.library.RunMainMenu().
Referenced by ce103_hw3_library_lib.library.BookOption().
BorrowBook()
void ce103_hw3_library_lib.BookFunctions.BorrowBook ()
References ce103_hw3_library_lib.FileUtility.ReadBlock(), ce103_hw3_library_lib.library.RunMainMenu(), and ce103_hw3_library_lib.FileUtility.UpdateBlock().
Referenced by ce103_hw3_library_lib.library.BookOption().
DeleteBook()
void ce103_hw3_library_lib.BookFunctions.DeleteBook ()
References ce103_hw3_library_lib.FileUtility.DeleteBlock(), and ce103_hw3_library_lib.library.RunMainMenu().
Referenced by ce103_hw3_library_lib.library.BookOption().
EditBook()
void ce103_hw3_library_lib.BookFunctions.EditBook ()
References ce103_hw3_library_lib.library.RunMainMenu(), and ce103_hw3_library_lib.FileUtility.UpdateBlock().
Referenced by ce103_hw3_library_lib.library.BookOption().
ListBook()
void ce103_hw3_library_lib.BookFunctions.ListBook ()
References ce103_hw3_library_lib.FileUtility.ReadBlock(), and ce103_hw3_library_lib.library.RunMainMenu().
Referenced by ce103_hw3_library_lib.library.BookOption().
ListBorrowBook()
void ce103_hw3_library_lib.BookFunctions.ListBorrowBook ()
References ce103_hw3_library_lib.FileUtility.ReadBlock(), and ce103_hw3_library_lib.library.RunMainMenu().
Referenced by ce103_hw3_library_lib.library.BookOption().
ReturnBook()
void ce103_hw3_library_lib.BookFunctions.ReturnBook ()
References ce103_hw3_library_lib.FileUtility.ReadBlock(), ce103_hw3_library_lib.library.RunMainMenu(), and ce103_hw3_library_lib.FileUtility.UpdateBlock().
Referenced by ce103_hw3_library_lib.library.BookOption().
SearchBook()
void ce103_hw3_library_lib.BookFunctions.SearchBook ()
References ce103_hw3_library_lib.FileUtility.ReadBlock(), and ce103_hw3_library_lib.library.RunMainMenu().
Referenced by ce103_hw3_library_lib.library.BookOption().
The documentation for this class was generated from the following file:
BookFunctions.cs