CE103 Homework 3 Eray Turan: ce103_hw3_library_lib.library Class Reference
ce103_hw3_library_lib.library Class Reference
Public Member Functions
void Start ()
void RunMainMenu ()
void BookOption ()
void Back ()
void ExitApp ()
Member Function Documentation
Back()
void ce103_hw3_library_lib.library.Back ()
References ce103_hw3_library_lib.library.RunMainMenu().
Referenced by ce103_hw3_library_lib.library.BookOption().
BookOption()
void ce103_hw3_library_lib.library.BookOption ()
References ce103_hw3_library_lib.BookFunctions.AddBook(), ce103_hw3_library_lib.library.Back(), ce103_hw3_library_lib.BookFunctions.BorrowBook(), ce103_hw3_library_lib.BookFunctions.DeleteBook(), ce103_hw3_library_lib.BookFunctions.EditBook(), ce103_hw3_library_lib.BookFunctions.ListBook(), ce103_hw3_library_lib.BookFunctions.ListBorrowBook(), ce103_hw3_library_lib.BookFunctions.ReturnBook(), ce103_hw3_library_lib.Menu.Run(), ce103_hw3_library_lib.library.RunMainMenu(), and ce103_hw3_library_lib.BookFunctions.SearchBook().
Referenced by ce103_hw3_library_lib.library.RunMainMenu().
ExitApp()
void ce103_hw3_library_lib.library.ExitApp ()
Referenced by ce103_hw3_library_lib.library.RunMainMenu().
RunMainMenu()
void ce103_hw3_library_lib.library.RunMainMenu ()
References ce103_hw3_library_lib.library.BookOption(), ce103_hw3_library_lib.library.ExitApp(), and ce103_hw3_library_lib.Menu.Run().
Referenced by ce103_hw3_library_lib.BookFunctions.AddBook(), ce103_hw3_library_lib.library.Back(), ce103_hw3_library_lib.library.BookOption(), ce103_hw3_library_lib.BookFunctions.BorrowBook(), ce103_hw3_library_lib.BookFunctions.DeleteBook(), ce103_hw3_library_lib.BookFunctions.EditBook(), ce103_hw3_library_lib.BookFunctions.ListBook(), ce103_hw3_library_lib.BookFunctions.ListBorrowBook(), ce103_hw3_library_lib.BookFunctions.ReturnBook(), ce103_hw3_library_lib.BookFunctions.SearchBook(), and ce103_hw3_library_lib.library.Start().
Start()
void ce103_hw3_library_lib.library.Start ()
References ce103_hw3_library_lib.library.RunMainMenu().
Referenced by ce103_hw3_library_lib.PasswordContent.password(), and ce103_hw3_library_lib.Menu.Run().
The documentation for this class was generated from the following file:
MainMenu.cs